version: '3.2'

services:
    ruby:
      build: ./ruby
      restart: unless-stopped
      ports:
        - "${WEB_PORT}:80"
      links:
        - plantuml
      volumes:
        - ./gollum-data:/wiki
        - ./ruby/config.rb:/config.rb:ro
      command: "gollum --port 80 --plantuml-url ${PLANTUML_URL_BASE} --config /config.rb"
    plantuml:
      image: plantuml/plantuml-server:jetty
      restart: unless-stopped
      ports:
        - "${PLANTUML_PORT}:8080"
