version: '3.2'

services:
    ruby:
      build: ./ruby
      restart: unless-stopped
      ports:
        - 32080:80
      links:
        - plantuml
      volumes:
        - ./gollum-data:/wiki
        - ./ruby/config.rb:/config.rb:ro
    plantuml:
      image: plantuml/plantuml-server:jetty
      restart: unless-stopped
      ports:
        - 32880:8080
