version: '3.2'

services:
    ruby:
      build: ./ruby
      restart: unless-stopped
      ports:
        - 30280:80
      links:
        - plantuml
      volumes:
        - ./gollum-data:/wiki
    plantuml:
      image: plantuml/plantuml-server:jetty
      restart: unless-stopped
