version: '3.2'

services:
    ruby:
      build: ./ruby
      restart: unless-stopped
      ports:
        - "${WEB_PORT}:80"
      volumes:
        - ./gollum-data:/wiki
        - ./ruby/config.rb:/config.rb:ro
      environment:
        PLANTUML_URL_BASE: ${PLANTUML_URL_BASE}
      command: "gollum --port 80 --config /config.rb"
    plantuml:
      image: plantuml/plantuml-server:jetty
      restart: unless-stopped
      ports:
        - "${PLANTUML_PORT}:8080"
